@startuml

start

fork
  :Open Terminal or CMD;
  note left
    Bot Developer asks Simulator
    to run a specific simulation.
  end note
fork again
  :Start Simulator Subprocess;
  note right
    Bot Training Program asks Simulator
    to run a specific simulation.
  end note
end fork

:Call Simulator Binary
With Specific Arguments;
note right
  **call format:**
  ./server
  --bot bots/test_bot
  --referee referees/referee
  --data maps/test_map.mlm
  --save_path simulations/simulation_1.mls
end note

if (bot path\nspecified?) then (no)
  :Bot Not Found;
  end
elseif (referee path\nspecified?) then (no)
  :Referee Not Found;
  end
elseif (init data\npath specified?) then (no)
  :No Data Found;
  end
elseif (save path\nspecified?) then (no)
  :Save Path
  Not Specified;
   end
else (preconditions\nsatisfied)
endif
:Execute Simulation;
:Save Under Specific Path;
:Return Success Code;

stop

@enduml
