@startuml

start

:Run Simulation;
note left
  Bot Developer or Bot Training Program
  asks system to run a specific simulation.
end note

if (bot path\nspecified?) then (no)
  :Bot Not Found;
  end
elseif (referee path\nspecified?) then (no)
  :Referee Not Found;
  end
elseif (init data\npath specified?) then (no)
  :No Data Found;
  end
elseif (save path\nspecified?) then (no)
  :Save Path
  Not Specified;
   end
else (preconditions\nsatisfied)
endif
:Execute Simulation;
:Save Under Specific Path;
:Return Success Code;

stop

@enduml
